name: Biocommons Hackathon Project Proposal
description: Project proposal for the Biocommons Hackathon
title: "[Hackathon project title]"

body:
  - type: input
    id: submitter_name
    attributes:
      label: Submitter Name
      placeholder: John Doe
    validations:
      required: true
  - type: input
    id: submitter_affiliation
    attributes:
      label: Submitter Affiliation
      placeholder: ABC Institution
    validations:
      required: true
  - type: input
    id: requested_by
    attributes:
      label: Requested By
      description: The project, organization, or group who requested this project
      placeholder: Invitae
    validations:
      required: true
  - type: textarea
    id: submitter_additional
    attributes:
      label: Additional Submitter Details
  - type: input
    id: leads
    attributes:
      label: Lead(s)
      description: Who will be leading this project at the hackathon
  - type: dropdown
    id: biocommons_repo
    attributes:
      label: biocommons Repo
      description: What biocommons repo is this project associated with?
      options:
        - seqrepo
        - seqrepo-rest
        - uta
        - hgvs
        - anyvar
        - eutils
        - bioutils
        - general (multiple biocommons repos)
    validations:
      required: true
  - type: textarea
    id: project_details
    attributes:
      label: Project Details
      description: Discuss what the project intends to accomplish
    validations:
      required: true
