name: Biocommons Hackathon Project Proposal
description: Project proposal for the Biocommons Hackathon
title: "[Hackathon project title]"

body:
  - type: input
    id: submitter_name
    attributes:
      label: Submitter Name
      placeholder: John Doe
    validations:
      required: true
  - type: input
    id: submitter_affiliation
    attributes:
      label: Submitter Affiliation
      placeholder: ABC Institution
    validations:
      required: true
  - type: textarea
    id: submitter_additional
    attributes:
      label: Additional Submitter Details
  - type: textarea
    id: project_details
    attributes:
      label: Project Details
      description: Discuss what the project intends to accomplish
    validations:
      required: true
  - type: textarea
    id: required_skills
    attributes:
      label: Required Skills
      description: List any skill set necessary or beneficial for participants to contribute to the project, e.g. Python, reStructuredText, Rust, UML
